### PR TITLE
#2 trying xu-cheng/latex-action instead yegor256/latexmk-action@0.1.16

### PR DESCRIPTION
**Pull request by CAMOBAP**

### CODE REVIEW

**Comment by ronaldtse** [comment]
@CAMOBAP yeah this action from xu-cheng requires `root-file` which demands a filename for a `.tex` file. In this case we have a "collection of .tex files" determined in `tex/latexmkrc`'s `@default_files` variable. Maybe we will have to split that out into the GitHub Action (or we generate the filenames via GHA `output` variable by some `grep` magic on the `latexmkrc` file).

**Comment by CAMOBAP** [comment]
@ronaldtse in `xu-cheng`'s action they aware of `latexmkrc` I just looking for a right example

**Comment by CAMOBAP** [comment]
@ronaldtse I think the fix is done, may I ask you to check the result PDFs? Log still reports not found files, but the process finishes successfully, also PDFs looks ok (as far as I can understand)

**Comment by ronaldtse** [comment]
This looks perfect. Thank you @CAMOBAP !

**Review by ronaldtse — APPROVED** [review]

**Pull request merged**
